### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DirkToewe** [nicolasstucki/scala-rrb-vector#9]
Hi @nicolasstucki,

I am looking into finally getting RRBVector into the Scala SDK. A lot of work was put into this by You and others. It's a shame that it didn't make its way there yet. In order to do that, I need You to add a License to this repository. Scala is licensed under unter Apache License V2.0 if I am not mistaken. Would You mind distributing Your code under the same License? If I file a PR, I will cite Your Thesis and this Repo as sources of course.

**Comment by nicolasstucki** [comment]
@DirkToewe  sorry for the slow response. I added the Apache 2.0 License. You should also link the ICFP paper as it is a bit more polished than the thesis. If you have any questions please feel free to ask me.

**Comment by jafingerhut** [comment]
@DirkToewe I have been looking at multiple RRB tree implementations, yet to find one that is free of known bugs -- concatenation in combination with the other operations makes for sometimes hard-to-reason-about code.  I may work on a battle-tested Java implementation soon, after having successfully fixed most (but not all) bugs in the Clojure RRB tree implementation, but wanting something with better performance than that library does right now.

I am unfamiliar with Scala, and having difficulties trying to get this Scala code running, and was curious if you (or anyone you know) has gotten it running with modern Scala, or perhaps even with nothing other than what is in the released JAR file on Maven central for this library?

**Comment by nicolasstucki** [comment]
I haven't used it in a while. Unfortunately I am not aware of who is using it. I could update the scala version and republish it in 2~3 weeks if that would help you.

**Comment by jafingerhut** [comment]
Thanks for the offer.  I have since gotten this code compiled and running with sbt 2.11.6, which the core/build.sbt file mentions, and also 2.11.12.  It seems like it would require changes, I have no idea how large or small, to compile and run with sbt 2.12.0 or later, due to changes in the Scala library.

I believe I can do whatever testing and learning I can from the code as it is.

**Comment by jafingerhut** [comment]
Correction: In my previous comment, all of the version numbers are for the Scala library, which I think are identical to the corresponding Scala compiler versions.  The latest version of sbt that I was successful in using with this code is 0.13.18.
